"""current baseline

Revision ID: 0001_current_baseline
Revises:
Create Date: 2026-08-01 02:59:22.586131
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001_current_baseline"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_evolution_candidates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("candidate_key", sa.String(length=240), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("supersedes_id", sa.String(length=36), nullable=True),
        sa.Column("candidate_type", sa.String(length=40), nullable=False),
        sa.Column("target_component", sa.String(length=80), nullable=False),
        sa.Column("namespace_type", sa.String(length=40), nullable=False),
        sa.Column("namespace_id", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column(
            "content",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("content_digest", sa.String(length=64), nullable=False),
        sa.Column(
            "source_manifest",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("source_manifest_digest", sa.String(length=64), nullable=False),
        sa.Column(
            "environment_constraints",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("current_evaluation_id", sa.String(length=36), nullable=True),
        sa.Column("created_by", sa.String(length=120), nullable=True),
        sa.Column("reviewed_by", sa.String(length=120), nullable=True),
        sa.Column("review_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["agent_evolution_candidates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "namespace_type",
            "namespace_id",
            "candidate_key",
            "revision",
            name="uq_agent_evolution_namespace_key_revision",
        ),
    )
    op.create_index(
        "ix_agent_evolution_namespace_status",
        "agent_evolution_candidates",
        ["namespace_type", "namespace_id", "status"],
        unique=False,
    )
    op.create_table(
        "conversation_strategy_preferences",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("preferred_answer_mode", sa.String(length=40), nullable=False),
        sa.Column("reasoning_effort", sa.String(length=40), nullable=False),
        sa.Column("max_tool_calls", sa.Integer(), nullable=True),
        sa.Column("reflection_enabled", sa.Boolean(), nullable=False),
        sa.Column("reflection_trigger", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "memory_consolidation_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("namespace_type", sa.String(length=40), nullable=False),
        sa.Column("namespace_id", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "input_manifest",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "proposal",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "validation",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "profile_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "model_usage",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "publish_result",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "error",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("lease_owner", sa.String(length=120), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rollback_of_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["rollback_of_id"],
            ["memory_consolidation_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_memory_consolidation_idempotency"),
    )
    op.create_index(
        "ix_memory_consolidation_lease",
        "memory_consolidation_jobs",
        ["status", "lease_expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_memory_consolidation_namespace_status",
        "memory_consolidation_jobs",
        ["namespace_type", "namespace_id", "status"],
        unique=False,
    )
    op.create_table(
        "skill_blobs",
        sa.Column("digest", sa.String(length=80), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("media_type", sa.String(length=160), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("digest"),
    )
    op.create_table(
        "skills",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("origin", sa.String(length=20), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("active_revision_id", sa.String(length=36), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_skills_name"),
    )
    op.create_index("ix_skills_origin_enabled", "skills", ["origin", "enabled"], unique=False)
    op.create_table(
        "tasks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("workspace_id", sa.String(length=120), nullable=True),
        sa.Column("created_by", sa.String(length=120), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("priority", sa.String(length=40), nullable=True),
        sa.Column("risk_level", sa.String(length=40), nullable=True),
        sa.Column("preferred_answer_mode", sa.String(length=40), nullable=False),
        sa.Column("title_source", sa.String(length=20), nullable=False),
        sa.Column(
            "context_state",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("pinned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_tasks_retention_scan", "tasks", ["pinned_at", "updated_at"], unique=False)
    op.create_table(
        "tool_settings",
        sa.Column("tool_name", sa.String(length=120), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("tool_name"),
    )
    op.create_table(
        "agent_evolution_audit_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("candidate_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("actor", sa.String(length=120), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("expected_state_version", sa.Integer(), nullable=True),
        sa.Column("actual_state_version", sa.Integer(), nullable=True),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["agent_evolution_candidates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_agent_evolution_audit_candidate_created",
        "agent_evolution_audit_events",
        ["candidate_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "agent_evolution_evaluations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("candidate_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "manifest",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("manifest_digest", sa.String(length=64), nullable=False),
        sa.Column("evaluator", sa.String(length=160), nullable=False),
        sa.Column("issuer", sa.String(length=160), nullable=False),
        sa.Column("verdict", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["agent_evolution_candidates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "candidate_id", "version", name="uq_agent_evolution_evaluation_version"
        ),
    )
    op.create_index(
        "ix_agent_evolution_evaluation_digest",
        "agent_evolution_evaluations",
        ["manifest_digest"],
        unique=False,
    )
    op.create_table(
        "conversation_shares",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("token", sa.String(length=120), nullable=False),
        sa.Column(
            "snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("conversation_id", name="uq_conversation_shares_conversation_id"),
        sa.UniqueConstraint("token", name="uq_conversation_shares_token"),
    )
    op.create_index(
        "ix_conversation_shares_conversation_id",
        "conversation_shares",
        ["conversation_id"],
        unique=False,
    )
    op.create_index("ix_conversation_shares_token", "conversation_shares", ["token"], unique=False)
    op.create_table(
        "runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("memory_session_id", sa.String(length=120), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("mode", sa.String(length=80), nullable=False),
        sa.Column("answer_mode", sa.String(length=40), nullable=False),
        sa.Column(
            "execution_profile",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "model_policy",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "agent_profile_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_step_id", sa.String(length=36), nullable=True),
        sa.Column("active_plan_id", sa.String(length=36), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "result",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "reasoning_policy",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "task_contract",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "plan_graph",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "agent_state",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column(
            "terminal_reason",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "waiting_state",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("task_adapter", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_runs_memory_session_id", "runs", ["memory_session_id"], unique=False)
    op.create_index("ix_runs_task_status", "runs", ["task_id", "status"], unique=False)
    op.create_table(
        "scheduled_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=240), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("system_key", sa.String(length=320), nullable=True),
        sa.Column("system_managed", sa.Boolean(), nullable=False),
        sa.Column("owner_principal", sa.String(length=240), nullable=True),
        sa.Column("target_task_id", sa.String(length=36), nullable=True),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("schedule_type", sa.String(length=40), nullable=False),
        sa.Column(
            "schedule",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("timezone", sa.String(length=120), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("misfire_policy", sa.String(length=40), nullable=False),
        sa.Column("misfire_grace_seconds", sa.Integer(), nullable=False),
        sa.Column("overlap_policy", sa.String(length=40), nullable=False),
        sa.Column(
            "execution",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "heartbeat",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("next_fire_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_fire_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_owner", sa.String(length=240), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["target_task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("system_key", name="uq_scheduled_jobs_system_key"),
    )
    op.create_index(
        "ix_scheduled_jobs_due",
        "scheduled_jobs",
        ["enabled", "deleted_at", "next_fire_at", "lease_expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_scheduled_jobs_target", "scheduled_jobs", ["target_task_id", "kind"], unique=False
    )
    op.create_table(
        "skill_audit_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("skill_id", sa.String(length=36), nullable=True),
        sa.Column("type", sa.String(length=120), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_skill_audit_skill_created",
        "skill_audit_events",
        ["skill_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "skill_drafts",
        sa.Column("skill_id", sa.String(length=36), nullable=False),
        sa.Column("revision_token", sa.String(length=36), nullable=False),
        sa.Column(
            "files",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "validation_report",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
        ),
        sa.PrimaryKeyConstraint("skill_id"),
    )
    op.create_table(
        "skill_revisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("skill_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("digest", sa.String(length=80), nullable=False),
        sa.Column(
            "frontmatter",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "manifest",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "validation_report",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("predecessor_id", sa.String(length=36), nullable=True),
        sa.Column("test_only", sa.Boolean(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["predecessor_id"],
            ["skill_revisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("skill_id", "version", name="uq_skill_revisions_version"),
    )
    op.create_index(
        "ix_skill_revisions_skill_published",
        "skill_revisions",
        ["skill_id", "published_at"],
        unique=False,
    )
    op.create_table(
        "task_workspaces",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column(
            "quotas",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id", name="uq_task_workspaces_task_id"),
    )
    op.create_table(
        "agent_identities",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=True),
        sa.Column("run_id", sa.String(length=36), nullable=True),
        sa.Column("parent_identity_id", sa.String(length=36), nullable=True),
        sa.Column("identity_type", sa.String(length=80), nullable=False),
        sa.Column("principal", sa.String(length=240), nullable=False),
        sa.Column("trust_level", sa.String(length=40), nullable=False),
        sa.Column(
            "attributes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_identity_id"],
            ["agent_identities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_agent_identities_run_type",
        "agent_identities",
        ["run_id", "identity_type"],
        unique=False,
    )
    op.create_index(
        "ix_agent_identities_task_type",
        "agent_identities",
        ["task_id", "identity_type"],
        unique=False,
    )
    op.create_table(
        "data_flow_states",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column(
            "trust_sources",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "data_labels",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "allowed_destinations",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "prohibited_destinations",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "retention",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", name="uq_data_flow_states_run_id"),
    )
    op.create_table(
        "evidence_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("evidence_id", sa.String(length=40), nullable=False),
        sa.Column("evidence_key", sa.String(length=320), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("payload_digest", sa.String(length=64), nullable=False),
        sa.Column(
            "fragment",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("plan_node_id", sa.String(length=36), nullable=True),
        sa.Column("node_execution_id", sa.String(length=36), nullable=True),
        sa.Column("tool_call_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "evidence_key", name="uq_evidence_records_run_key"),
    )
    op.create_index(
        "ix_evidence_records_run_kind", "evidence_records", ["run_id", "kind"], unique=False
    )
    op.create_index(
        "ix_evidence_records_tool_call", "evidence_records", ["tool_call_id"], unique=False
    )
    op.create_table(
        "memories",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=True),
        sa.Column("created_by", sa.String(length=120), nullable=True),
        sa.Column("memory_key", sa.String(length=240), nullable=False),
        sa.Column("namespace_type", sa.String(length=40), nullable=False),
        sa.Column("namespace_id", sa.String(length=120), nullable=False),
        sa.Column("scope", sa.String(length=40), nullable=False),
        sa.Column("kind", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "structured_data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "provenance",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("importance", sa.Float(), nullable=False),
        sa.Column("utility_score", sa.Float(), nullable=False),
        sa.Column("access_count", sa.Integer(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("supersedes_id", sa.String(length=36), nullable=True),
        sa.Column("consolidation_generation", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_accessed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoke_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["memories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "namespace_type",
            "namespace_id",
            "memory_key",
            "version",
            name="uq_memories_namespace_key_version",
        ),
    )
    op.create_index("ix_memories_key_version", "memories", ["memory_key", "version"], unique=False)
    op.create_index(
        "ix_memories_namespace_status_kind",
        "memories",
        ["namespace_type", "namespace_id", "status", "kind"],
        unique=False,
    )
    op.create_index("ix_memories_scope_kind", "memories", ["scope", "kind"], unique=False)
    op.create_index("ix_memories_status_expiry", "memories", ["status", "expires_at"], unique=False)
    op.create_table(
        "model_invocations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("turn_id", sa.String(length=36), nullable=True),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("model", sa.String(length=160), nullable=False),
        sa.Column("operation", sa.String(length=80), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("cached_input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("reasoning_tokens", sa.Integer(), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=True),
        sa.Column("provider_request_id", sa.String(length=240), nullable=True),
        sa.Column(
            "raw_usage",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("error_type", sa.String(length=160), nullable=True),
        sa.Column("error_code", sa.String(length=160), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_model_invocations_provider_model",
        "model_invocations",
        ["provider", "model"],
        unique=False,
    )
    op.create_index(
        "ix_model_invocations_run_created",
        "model_invocations",
        ["run_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_model_invocations_status_created",
        "model_invocations",
        ["status", "created_at"],
        unique=False,
    )
    op.create_table(
        "plans",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("supersedes_plan_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_plan_id"],
            ["plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "version", name="uq_plans_run_version"),
    )
    op.create_index("ix_plans_run_status", "plans", ["run_id", "status"], unique=False)
    op.create_table(
        "run_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=80), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_run_events_run_id_id", "run_events", ["run_id", "id"], unique=False)
    op.create_table(
        "run_skill_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("catalog_digest", sa.String(length=80), nullable=False),
        sa.Column(
            "catalog",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "activations",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "resource_reads",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("answer_mode", sa.String(length=40), nullable=False),
        sa.Column("draft_test", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", name="uq_run_skill_snapshots_run"),
    )
    op.create_index(
        "ix_run_skill_snapshots_catalog_digest",
        "run_skill_snapshots",
        ["catalog_digest"],
        unique=False,
    )
    op.create_table(
        "scheduled_job_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column("idempotency_key", sa.String(length=320), nullable=False),
        sa.Column("trigger_type", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("claimed_by", sa.String(length=240), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("task_id", sa.String(length=36), nullable=True),
        sa.Column("run_id", sa.String(length=36), nullable=True),
        sa.Column(
            "outcome",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["scheduled_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_scheduled_job_runs_idempotency_key"),
        sa.UniqueConstraint(
            "job_id", "scheduled_for", name="uq_scheduled_job_runs_job_scheduled_for"
        ),
    )
    op.create_index(
        "ix_scheduled_job_runs_job_created",
        "scheduled_job_runs",
        ["job_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_scheduled_job_runs_status_claimed",
        "scheduled_job_runs",
        ["status", "claimed_at"],
        unique=False,
    )
    op.create_table(
        "steps",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("intent", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column(
            "depends_on",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "evidence",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_steps_run_id_index", "steps", ["run_id", "index"], unique=False)
    op.create_table(
        "tool_catalog_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column(
            "catalog",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("digest", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", name="uq_tool_catalog_snapshots_run_id"),
    )
    op.create_table(
        "workspace_checkpoints",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column(
            "manifest",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("manifest_hash", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["task_workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_workspace_checkpoints_workspace_created",
        "workspace_checkpoints",
        ["workspace_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "workspace_files",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("relative_path", sa.String(length=1000), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("mime_type", sa.String(length=160), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("checksum", sa.String(length=120), nullable=True),
        sa.Column("security_status", sa.String(length=40), nullable=False),
        sa.Column("deliverable_candidate", sa.Boolean(), nullable=False),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["task_workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "relative_path", name="uq_workspace_files_path"),
    )
    op.create_index(
        "ix_workspace_files_workspace_status",
        "workspace_files",
        ["workspace_id", "status"],
        unique=False,
    )
    op.create_table(
        "agent_delegations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("parent_identity_id", sa.String(length=36), nullable=False),
        sa.Column("child_identity_id", sa.String(length=36), nullable=False),
        sa.Column(
            "delegated_scope",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["child_identity_id"],
            ["agent_identities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_identity_id"],
            ["agent_identities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "parent_identity_id", "child_identity_id", name="uq_agent_delegations_parent_child"
        ),
    )
    op.create_index(
        "ix_agent_delegations_parent",
        "agent_delegations",
        ["parent_identity_id", "revoked_at"],
        unique=False,
    )
    op.create_table(
        "agent_evolution_sources",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("candidate_id", sa.String(length=36), nullable=False),
        sa.Column("source_kind", sa.String(length=40), nullable=False),
        sa.Column("source_ref", sa.String(length=320), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=True),
        sa.Column("memory_id", sa.String(length=36), nullable=True),
        sa.Column(
            "source_data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("accessible", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["agent_evolution_candidates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["memory_id"],
            ["memories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "candidate_id",
            "source_kind",
            "source_ref",
            name="uq_agent_evolution_sources_candidate_kind_ref",
        ),
    )
    op.create_index(
        "ix_agent_evolution_sources_run", "agent_evolution_sources", ["run_id"], unique=False
    )
    op.create_table(
        "credential_grants",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("agent_identity_id", sa.String(length=36), nullable=False),
        sa.Column("service", sa.String(length=160), nullable=False),
        sa.Column("tenant", sa.String(length=240), nullable=True),
        sa.Column(
            "scopes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "resources",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "actions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_identity_id"],
            ["agent_identities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_credential_grants_run_service", "credential_grants", ["run_id", "service"], unique=False
    )
    op.create_index(
        "ix_credential_grants_task_revoked",
        "credential_grants",
        ["task_id", "revoked_at"],
        unique=False,
    )
    op.create_table(
        "memory_audit_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("memory_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("actor", sa.String(length=120), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["memory_id"],
            ["memories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_memory_audit_memory_created",
        "memory_audit_events",
        ["memory_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "memory_links",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_memory_id", sa.String(length=36), nullable=False),
        sa.Column("target_memory_id", sa.String(length=36), nullable=False),
        sa.Column("relation", sa.String(length=40), nullable=False),
        sa.Column(
            "link_data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_memory_id"],
            ["memories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_memory_id"],
            ["memories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_memory_id",
            "target_memory_id",
            "relation",
            name="uq_memory_links_source_target_relation",
        ),
    )
    op.create_index(
        "ix_memory_links_target_relation",
        "memory_links",
        ["target_memory_id", "relation"],
        unique=False,
    )
    op.create_table(
        "plan_nodes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("plan_id", sa.String(length=36), nullable=False),
        sa.Column("node_key", sa.String(length=120), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("intent", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column(
            "required_capabilities",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "required_skill_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "success_criteria_refs",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "expected_outcome",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("risk_level", sa.String(length=40), nullable=False),
        sa.Column("optional", sa.Boolean(), nullable=False),
        sa.Column(
            "evidence_refs",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "failure",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("lineage_node_id", sa.String(length=36), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["lineage_node_id"],
            ["plan_nodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plan_id", "index", name="uq_plan_nodes_plan_index"),
        sa.UniqueConstraint("plan_id", "node_key", name="uq_plan_nodes_plan_key"),
    )
    op.create_index("ix_plan_nodes_plan_status", "plan_nodes", ["plan_id", "status"], unique=False)
    op.create_table(
        "node_executions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("plan_id", sa.String(length=36), nullable=False),
        sa.Column("plan_version", sa.Integer(), nullable=False),
        sa.Column("plan_node_id", sa.String(length=36), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("dispatch_batch_id", sa.String(length=36), nullable=False),
        sa.Column("worker_id", sa.String(length=120), nullable=True),
        sa.Column("phase", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("current_slot", sa.String(length=16), nullable=True),
        sa.Column("slot_index", sa.Integer(), nullable=True),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("wait_reason", sa.String(length=80), nullable=True),
        sa.Column(
            "checkpoint",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "result",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "failure",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_node_id"],
            ["plan_nodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plan_node_id", "attempt", name="uq_node_executions_node_attempt"),
        sa.UniqueConstraint("plan_node_id", "current_slot", name="uq_node_executions_current_slot"),
        sa.UniqueConstraint("run_id", "slot_index", name="uq_node_executions_run_slot"),
    )
    op.create_index(
        "ix_node_executions_heartbeat", "node_executions", ["status", "heartbeat_at"], unique=False
    )
    op.create_index(
        "ix_node_executions_plan_status", "node_executions", ["plan_id", "status"], unique=False
    )
    op.create_index(
        "ix_node_executions_run_status", "node_executions", ["run_id", "status"], unique=False
    )
    op.create_table(
        "plan_edges",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("plan_id", sa.String(length=36), nullable=False),
        sa.Column("predecessor_id", sa.String(length=36), nullable=False),
        sa.Column("successor_id", sa.String(length=36), nullable=False),
        sa.Column("dependency_type", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["predecessor_id"],
            ["plan_nodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["successor_id"],
            ["plan_nodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "plan_id", "predecessor_id", "successor_id", name="uq_plan_edges_nodes"
        ),
    )
    op.create_index("ix_plan_edges_successor", "plan_edges", ["successor_id"], unique=False)
    op.create_table(
        "agent_turns",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("plan_node_id", sa.String(length=36), nullable=True),
        sa.Column("node_execution_id", sa.String(length=36), nullable=True),
        sa.Column("turn_index", sa.Integer(), nullable=False),
        sa.Column("decision_type", sa.String(length=40), nullable=False),
        sa.Column("reasoning_summary", sa.Text(), nullable=False),
        sa.Column("selected_tool", sa.String(length=120), nullable=True),
        sa.Column(
            "decision",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "observation",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "reflection",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("tool_call_id", sa.String(length=36), nullable=True),
        sa.Column("artifact_id", sa.String(length=36), nullable=True),
        sa.Column(
            "memory_reads",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "memory_writes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column(
            "evaluation",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "reflection_patch",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("state_version_before", sa.Integer(), nullable=True),
        sa.Column("state_version_after", sa.Integer(), nullable=True),
        sa.Column("plan_version", sa.Integer(), nullable=False),
        sa.Column("phase", sa.String(length=40), nullable=False),
        sa.Column("idempotency_key", sa.String(length=120), nullable=True),
        sa.Column("paused_node", sa.String(length=80), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_execution_id"],
            ["node_executions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_node_id"],
            ["plan_nodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_agent_turns_run_id_index", "agent_turns", ["run_id", "turn_index"], unique=False
    )
    op.create_table(
        "budget_reservations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("node_execution_id", sa.String(length=36), nullable=False),
        sa.Column("budget_kind", sa.String(length=40), nullable=False),
        sa.Column("reserved", sa.Integer(), nullable=False),
        sa.Column("consumed", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["node_execution_id"],
            ["node_executions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "node_execution_id", "budget_kind", name="uq_budget_reservations_execution_kind"
        ),
    )
    op.create_index(
        "ix_budget_reservations_run_status",
        "budget_reservations",
        ["run_id", "status"],
        unique=False,
    )
    op.create_table(
        "resource_leases",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("node_execution_id", sa.String(length=36), nullable=False),
        sa.Column("resource_key", sa.String(length=240), nullable=False),
        sa.Column("resource_summary", sa.String(length=160), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("fencing_token", sa.Integer(), nullable=False),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("release_reason", sa.String(length=80), nullable=True),
        sa.ForeignKeyConstraint(
            ["node_execution_id"],
            ["node_executions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "node_execution_id",
            "resource_key",
            "mode",
            name="uq_resource_leases_execution_resource_mode",
        ),
    )
    op.create_index(
        "ix_resource_leases_resource_active",
        "resource_leases",
        ["resource_key", "released_at"],
        unique=False,
    )
    op.create_index(
        "ix_resource_leases_run_active",
        "resource_leases",
        ["run_id", "released_at", "expires_at"],
        unique=False,
    )
    op.create_table(
        "tool_calls",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("step_id", sa.String(length=36), nullable=True),
        sa.Column("plan_node_id", sa.String(length=36), nullable=True),
        sa.Column("node_execution_id", sa.String(length=36), nullable=True),
        sa.Column("tool_name", sa.String(length=120), nullable=False),
        sa.Column("tool_version", sa.String(length=40), nullable=False),
        sa.Column(
            "input",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "output",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("permission", sa.String(length=80), nullable=False),
        sa.Column("side_effect_level", sa.String(length=80), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "error",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["node_execution_id"],
            ["node_executions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_node_id"],
            ["plan_nodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["steps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_tool_calls_run_id", "tool_calls", ["run_id"], unique=False)
    op.create_table(
        "approval_requests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("turn_id", sa.String(length=36), nullable=False),
        sa.Column("tool_call_id", sa.String(length=36), nullable=False),
        sa.Column("node_execution_id", sa.String(length=36), nullable=True),
        sa.Column("execution_attempt", sa.Integer(), nullable=True),
        sa.Column("expected_execution_state_version", sa.Integer(), nullable=True),
        sa.Column("tool_name", sa.String(length=120), nullable=False),
        sa.Column("tool_version", sa.String(length=40), nullable=False),
        sa.Column(
            "frozen_input",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "frozen_effect_plan",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("effect_plan_hash", sa.String(length=80), nullable=True),
        sa.Column("analyzer_version", sa.String(length=80), nullable=True),
        sa.Column("analyzer_digest", sa.String(length=120), nullable=True),
        sa.Column(
            "reviewer_identity",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("preview", sa.Text(), nullable=False),
        sa.Column("permission", sa.String(length=80), nullable=False),
        sa.Column("impact", sa.String(length=80), nullable=False),
        sa.Column(
            "similar_matcher",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("decision", sa.String(length=40), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["node_execution_id"],
            ["node_executions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tool_call_id"],
            ["tool_calls.id"],
        ),
        sa.ForeignKeyConstraint(
            ["turn_id"],
            ["agent_turns.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tool_call_id", name="uq_approval_requests_tool_call_id"),
    )
    op.create_index(
        "ix_approval_requests_run_status", "approval_requests", ["run_id", "status"], unique=False
    )
    op.create_table(
        "memory_recall_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("turn_id", sa.String(length=36), nullable=True),
        sa.Column("query_hash", sa.String(length=64), nullable=False),
        sa.Column("policy_version", sa.String(length=40), nullable=False),
        sa.Column(
            "namespace_manifest",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "candidates",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "selected",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "excluded",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "feedback",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["turn_id"],
            ["agent_turns.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_memory_recall_events_query_hash", "memory_recall_events", ["query_hash"], unique=False
    )
    op.create_index(
        "ix_memory_recall_events_run_created",
        "memory_recall_events",
        ["run_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "sandbox_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("tool_call_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column(
            "runtime_profile",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "resource_limits",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "input_artifact_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "output_artifact_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("executor", sa.String(length=80), nullable=False),
        sa.Column("runtime_name", sa.String(length=120), nullable=True),
        sa.Column("image_digest", sa.String(length=240), nullable=True),
        sa.Column("exit_reason", sa.String(length=120), nullable=True),
        sa.Column(
            "error",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("stdout_summary", sa.Text(), nullable=True),
        sa.Column("stderr_summary", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tool_call_id"],
            ["tool_calls.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "workspace_changes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("tool_call_id", sa.String(length=36), nullable=True),
        sa.Column("checkpoint_id", sa.String(length=36), nullable=True),
        sa.Column("relative_path", sa.String(length=1000), nullable=False),
        sa.Column("change_kind", sa.String(length=40), nullable=False),
        sa.Column("before_checksum", sa.String(length=120), nullable=True),
        sa.Column("after_checksum", sa.String(length=120), nullable=True),
        sa.Column("mime_type", sa.String(length=160), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("security_status", sa.String(length=40), nullable=False),
        sa.Column("deliverable_candidate", sa.Boolean(), nullable=False),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["checkpoint_id"],
            ["workspace_checkpoints.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tool_call_id"],
            ["tool_calls.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["task_workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_workspace_changes_run_created",
        "workspace_changes",
        ["run_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_workspace_changes_workspace_path",
        "workspace_changes",
        ["workspace_id", "relative_path"],
        unique=False,
    )
    op.create_table(
        "approval_grants",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=True),
        sa.Column("scope", sa.String(length=40), nullable=False),
        sa.Column(
            "subject",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("tool_name", sa.String(length=120), nullable=False),
        sa.Column("tool_version", sa.String(length=40), nullable=False),
        sa.Column(
            "matcher",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "effect_kinds",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "resource_matcher",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "invocation_constraints",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("source_approval_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("max_uses", sa.Integer(), nullable=True),
        sa.Column("use_count", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_approval_id"],
            ["approval_requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_approval_grants_run_tool", "approval_grants", ["run_id", "tool_name"], unique=False
    )
    op.create_index(
        "ix_approval_grants_task_scope",
        "approval_grants",
        ["task_id", "scope", "status"],
        unique=False,
    )
    op.create_table(
        "artifacts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=80), nullable=False),
        sa.Column("path", sa.String(length=500), nullable=True),
        sa.Column("content_ref", sa.Text(), nullable=True),
        sa.Column("tool_call_id", sa.String(length=36), nullable=True),
        sa.Column("plan_node_id", sa.String(length=36), nullable=True),
        sa.Column("sandbox_job_id", sa.String(length=36), nullable=True),
        sa.Column("mime_type", sa.String(length=160), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("checksum", sa.String(length=80), nullable=True),
        sa.Column("storage_key", sa.String(length=500), nullable=True),
        sa.Column("preview_key", sa.String(length=500), nullable=True),
        sa.Column("security_status", sa.String(length=40), nullable=False),
        sa.Column(
            "provenance",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_node_id"],
            ["plan_nodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sandbox_job_id"],
            ["sandbox_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tool_call_id"],
            ["tool_calls.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "memory_sources",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("memory_id", sa.String(length=36), nullable=False),
        sa.Column("source_kind", sa.String(length=40), nullable=False),
        sa.Column("source_ref", sa.String(length=320), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=True),
        sa.Column("turn_id", sa.String(length=36), nullable=True),
        sa.Column("tool_call_id", sa.String(length=36), nullable=True),
        sa.Column("artifact_id", sa.String(length=36), nullable=True),
        sa.Column(
            "source_data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("accessible", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["artifacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["memory_id"],
            ["memories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tool_call_id"],
            ["tool_calls.id"],
        ),
        sa.ForeignKeyConstraint(
            ["turn_id"],
            ["agent_turns.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "memory_id", "source_kind", "source_ref", name="uq_memory_sources_memory_kind_ref"
        ),
    )
    op.create_index(
        "ix_memory_sources_memory_accessible",
        "memory_sources",
        ["memory_id", "accessible"],
        unique=False,
    )
    op.create_index("ix_memory_sources_run", "memory_sources", ["run_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_memory_sources_run", table_name="memory_sources")
    op.drop_index("ix_memory_sources_memory_accessible", table_name="memory_sources")
    op.drop_table("memory_sources")
    op.drop_table("artifacts")
    op.drop_index("ix_approval_grants_task_scope", table_name="approval_grants")
    op.drop_index("ix_approval_grants_run_tool", table_name="approval_grants")
    op.drop_table("approval_grants")
    op.drop_index("ix_workspace_changes_workspace_path", table_name="workspace_changes")
    op.drop_index("ix_workspace_changes_run_created", table_name="workspace_changes")
    op.drop_table("workspace_changes")
    op.drop_table("sandbox_jobs")
    op.drop_index("ix_memory_recall_events_run_created", table_name="memory_recall_events")
    op.drop_index("ix_memory_recall_events_query_hash", table_name="memory_recall_events")
    op.drop_table("memory_recall_events")
    op.drop_index("ix_approval_requests_run_status", table_name="approval_requests")
    op.drop_table("approval_requests")
    op.drop_index("ix_tool_calls_run_id", table_name="tool_calls")
    op.drop_table("tool_calls")
    op.drop_index("ix_resource_leases_run_active", table_name="resource_leases")
    op.drop_index("ix_resource_leases_resource_active", table_name="resource_leases")
    op.drop_table("resource_leases")
    op.drop_index("ix_budget_reservations_run_status", table_name="budget_reservations")
    op.drop_table("budget_reservations")
    op.drop_index("ix_agent_turns_run_id_index", table_name="agent_turns")
    op.drop_table("agent_turns")
    op.drop_index("ix_plan_edges_successor", table_name="plan_edges")
    op.drop_table("plan_edges")
    op.drop_index("ix_node_executions_run_status", table_name="node_executions")
    op.drop_index("ix_node_executions_plan_status", table_name="node_executions")
    op.drop_index("ix_node_executions_heartbeat", table_name="node_executions")
    op.drop_table("node_executions")
    op.drop_index("ix_plan_nodes_plan_status", table_name="plan_nodes")
    op.drop_table("plan_nodes")
    op.drop_index("ix_memory_links_target_relation", table_name="memory_links")
    op.drop_table("memory_links")
    op.drop_index("ix_memory_audit_memory_created", table_name="memory_audit_events")
    op.drop_table("memory_audit_events")
    op.drop_index("ix_credential_grants_task_revoked", table_name="credential_grants")
    op.drop_index("ix_credential_grants_run_service", table_name="credential_grants")
    op.drop_table("credential_grants")
    op.drop_index("ix_agent_evolution_sources_run", table_name="agent_evolution_sources")
    op.drop_table("agent_evolution_sources")
    op.drop_index("ix_agent_delegations_parent", table_name="agent_delegations")
    op.drop_table("agent_delegations")
    op.drop_index("ix_workspace_files_workspace_status", table_name="workspace_files")
    op.drop_table("workspace_files")
    op.drop_index("ix_workspace_checkpoints_workspace_created", table_name="workspace_checkpoints")
    op.drop_table("workspace_checkpoints")
    op.drop_table("tool_catalog_snapshots")
    op.drop_index("ix_steps_run_id_index", table_name="steps")
    op.drop_table("steps")
    op.drop_index("ix_scheduled_job_runs_status_claimed", table_name="scheduled_job_runs")
    op.drop_index("ix_scheduled_job_runs_job_created", table_name="scheduled_job_runs")
    op.drop_table("scheduled_job_runs")
    op.drop_index("ix_run_skill_snapshots_catalog_digest", table_name="run_skill_snapshots")
    op.drop_table("run_skill_snapshots")
    op.drop_index("ix_run_events_run_id_id", table_name="run_events")
    op.drop_table("run_events")
    op.drop_index("ix_plans_run_status", table_name="plans")
    op.drop_table("plans")
    op.drop_index("ix_model_invocations_status_created", table_name="model_invocations")
    op.drop_index("ix_model_invocations_run_created", table_name="model_invocations")
    op.drop_index("ix_model_invocations_provider_model", table_name="model_invocations")
    op.drop_table("model_invocations")
    op.drop_index("ix_memories_status_expiry", table_name="memories")
    op.drop_index("ix_memories_scope_kind", table_name="memories")
    op.drop_index("ix_memories_namespace_status_kind", table_name="memories")
    op.drop_index("ix_memories_key_version", table_name="memories")
    op.drop_table("memories")
    op.drop_index("ix_evidence_records_tool_call", table_name="evidence_records")
    op.drop_index("ix_evidence_records_run_kind", table_name="evidence_records")
    op.drop_table("evidence_records")
    op.drop_table("data_flow_states")
    op.drop_index("ix_agent_identities_task_type", table_name="agent_identities")
    op.drop_index("ix_agent_identities_run_type", table_name="agent_identities")
    op.drop_table("agent_identities")
    op.drop_table("task_workspaces")
    op.drop_index("ix_skill_revisions_skill_published", table_name="skill_revisions")
    op.drop_table("skill_revisions")
    op.drop_table("skill_drafts")
    op.drop_index("ix_skill_audit_skill_created", table_name="skill_audit_events")
    op.drop_table("skill_audit_events")
    op.drop_index("ix_scheduled_jobs_target", table_name="scheduled_jobs")
    op.drop_index("ix_scheduled_jobs_due", table_name="scheduled_jobs")
    op.drop_table("scheduled_jobs")
    op.drop_index("ix_runs_task_status", table_name="runs")
    op.drop_index("ix_runs_memory_session_id", table_name="runs")
    op.drop_table("runs")
    op.drop_index("ix_conversation_shares_token", table_name="conversation_shares")
    op.drop_index("ix_conversation_shares_conversation_id", table_name="conversation_shares")
    op.drop_table("conversation_shares")
    op.drop_index("ix_agent_evolution_evaluation_digest", table_name="agent_evolution_evaluations")
    op.drop_table("agent_evolution_evaluations")
    op.drop_index(
        "ix_agent_evolution_audit_candidate_created", table_name="agent_evolution_audit_events"
    )
    op.drop_table("agent_evolution_audit_events")
    op.drop_table("tool_settings")
    op.drop_index("ix_tasks_retention_scan", table_name="tasks")
    op.drop_table("tasks")
    op.drop_index("ix_skills_origin_enabled", table_name="skills")
    op.drop_table("skills")
    op.drop_table("skill_blobs")
    op.drop_index(
        "ix_memory_consolidation_namespace_status", table_name="memory_consolidation_jobs"
    )
    op.drop_index("ix_memory_consolidation_lease", table_name="memory_consolidation_jobs")
    op.drop_table("memory_consolidation_jobs")
    op.drop_table("conversation_strategy_preferences")
    op.drop_index("ix_agent_evolution_namespace_status", table_name="agent_evolution_candidates")
    op.drop_table("agent_evolution_candidates")
    # ### end Alembic commands ###
